logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.gs.gestaoativos.services: DEBUG

security:
  enabled: true

